### ISSUE TITLE
Uitwerking van 'findShortestString' methode in Streams klopt niet.

### ISSUE THREAD

**Issue by RubenEppink** [HANICA-DEA/exercise-streams#2]
return input.stream().sorted().findFirst().orElse(null); 

Bovenstaande is de huidige uitwerking en werkt prima met de unittest die er momenteel voor gemaakt is. Helaas werkt deze uitwerking niet met elke lijst van Strings.

sorted() sorteert niet (alleen) op basis van een String met de het minste/meeste aantal karakters, waardoor er niet altijd het verwachte resultaat uitkomt. Kijk maar naar het volgende voorbeeld: 
("Geeks", "for", "GeeksQuiz", "GeeksforGeeks", "GFG") wordt met sorted() het volgende: 

GFG
Geeks
GeeksQuiz
GeeksforGeeks
for

Je ziet dus bijvoorbeeld het woord "for" niet als eerste voorkomt in de gesorteerde lijst, terwijl dit wel het woord is met het minste aantal karakters dat als eerst in de originele lijst voorkomt. 

als je daadwerkelijk wil sorteren op de het eerste kortste woord die in een lijst staat, dan kun je één van de volgende uitwerking gebruiken:

Uitwerking 1 is van stackoverflow: return input.stream().sorted((e2, e1) -> e1.length() > e2.length() ? -1 : 1).findFirst().get();

Uitwerking 2 is zelf bedacht: return input.stream()
                .filter(word -> word.length() ==
                input.stream()
                        .map(String::length)
                        .sorted().findFirst()
                        .get())
                .findFirst()
                .get();

Het zijn wellicht niet de meest elegante oplossingen, maar beter dan een niet werkende oplossing :-).  Hopelijk is het probleem zo voldoende toegelicht.

Bronnen: https://www.geeksforgeeks.org/stream-sorted-in-java/
https://stackoverflow.com/questions/25829866/finding-the-shortest-word-in-an-array-of-strings-java
en zelf gemaakte unittesten :)

**Comment by rodymiddelkoop** [comment]
Je kunt in dit geval het beste een comparator aan de sortering meegeven. Sorted pakt default de String-sortering (op volgorde waarin de karakters in de ASCII-tabel staan), maar je kunt verschillende andere comparators meegeven zoals bijv. op https://www.geeksforgeeks.org/stream-sorted-comparator-comparator-method-java/.
